#server:
 # port: 8080
#spring:
 # datasource:
  # url: jdbc:h2:mem:testdb
  # driverClassName: org.h2.Driver
  # username: sa
  # password: ''
#h2:
   #console:
     #enabled: true
#jpa:
   #database-platform: org.hibernate.dialect.H2Dialect
   #hibernate:
     #ddl-auto: update
     #show-sql: true

# PostgreSQL connection supabase
#server:
#  port: 8080
#spring:
#  datasource:
#    url: jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres
#    username: postgres.grtdjgzzaimrdtgqqsym
#    password: SuperSummer-2025!

  # Hibernate / JPA
 # jpa:
 #   database-platform: org.hibernate.dialect.PostgreSQLDialect
 #   hibernate:
 #     ddl-auto: update
 #   show-sql: true

# PostgreSQL connection Render
server:
  port: 8080
spring:
 datasource:
    url: jdbc:postgresql://dpg-d0mcutbe5dus738dpki0-a.oregon-postgres.render.com:5432/psdbname?sslmode=require
    username: ccsoudal
    password: cOPJMkWtA7mRWWwdqbhvVJpWVkafwGIC

# Hibernate / JPA
 jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
     ddl-auto: update
   show-sql: true